pub mod advanced;
pub mod analyze;
pub mod auto;
pub mod auto_color;
pub mod color_engine;
pub mod detail;
pub mod detect_spots;
pub mod export;
pub mod geometry;
pub mod guardrail;
pub mod heal;
pub mod params;
pub mod perceptual;
pub mod pipeline;
// 自动保存会话的序列化/反序列化（崩溃/误关恢复），从 crate 根直接暴露，便于 UI 调用。
pub use pipeline::{load_session_json, save_session_json};
pub mod preset;
pub mod reference;
pub mod schema;
pub mod sharpen;
pub mod spatial;
pub mod spot;
pub mod tonemap;
